title: Alberto Martín Visciglia # your name (or website title) here
logo: "/images/fotoredonda.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  <h1>Mathematics , Data Science | Machine Learning</h1>
  <b>Data Scientist with a deep passion for solving problems that affect people's lives<b>
  <a href="https://www.linkedin.com/in/alberto-visciglia/">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
